sonar.projectKey=crgolden_Experience
sonar.organization=crgolden

sonar.sources=Experience.Server,experience.client/src
sonar.tests=Experience.Tests
sonar.exclusions=experience.client/aspnetcore-https.js,experience.client/start-os.js,**/bin/**,**/obj/**,**/node_modules/**,**/*.d.ts
sonar.coverage.exclusions=experience.client/e2e/**,experience.client/src/test-setup.ts
sonar.test.inclusions=**/*.spec.ts

sonar.cs.vscoveragexml.reportsPaths=coverage.xml,coverage-e2e.xml
sonar.javascript.lcov.reportPaths=experience.client/coverage/lcov.info
